### ISSUE TITLE
StaticStringy v2 implementation is a regression

### ISSUE THREAD

**Issue by Bilge** [danielstjules/Stringy#106]
I use the static implementation, `StaticStringy` exclusively, but the v2 implementation is a regression. You might argue it's less maintenance overhead with the magic method implementation presently, but it's not, because you still have the maintenance burden of maintaining a list of valid methods and argument counts. Therefore I strongly recommend you revert to the v1 implementation for `StaticStringly`.

If you cannot be persuaded to revert, I strongly suggest you add `@method` annotations for the `StaticStringy` class. The v2 implementation breaks static analysis in editors meaning features like code insight/code completion do not work. Adding the `@method` annotations for each method exported by the class will fix this, but again, the maintenance overhead begins to bloom so much that you may as well just revert to the v1 implementation; moreover magic methods incur a performance hit.

I earnestly cannot see any tangible benefit to the v2 implementation at all and implore you to revert it. In the meantime my Composer definition will remain locked to v1.

**Comment by danielstjules** [comment]
https://github.com/danielstjules/Stringy/pull/105

**Comment by danielstjules** [comment]
> You might argue it's less maintenance overhead with the magic method implementation presently, but it's not, because you still have the maintenance burden of maintaining a list of valid methods and argument counts.

At this point, I think I'd prefer this
```php
/**
 * Class StaticStringy
 * ...
 * @method static string reverse(string $stringInput, string $encoding = null)
 * @method static string safeTruncate(string $stringInput, int $length, string $substring = '', string $encoding = null)
 * ...
 * @package Stringy
 */
protected static $methodArgs = array(
//...
        'reverse'                => 2,
        'safeTruncate'           => 4,
//...
);
```
to:
```php
    /**
     * Returns a reversed string. A multibyte version of strrev().
     *
     * @param  string $str      String to reverse
     * @param  string $encoding The character encoding
     * @return string The reversed string
     */
    public static function reverse($str, $encoding = null)
    {
        return (string) Stringy::create($str, $encoding)->reverse();
    }

    /**
     * Truncates the string to a given length, while ensuring that it does not
     * split words. If $substring is provided, and truncating occurs, the
     * string is further truncated so that the substring may be appended without
     * exceeding the desired length.
     *
     * @param  string $str       String to truncate
     * @param  int    $length    Desired length of the truncated string
     * @param  string $substring The substring to append if it can fit
     * @param  string $encoding  The character encoding
     * @return string The resulting string after truncating
     */
    public static function safeTruncate($str, $length, $substring = '',
                                        $encoding = null)
    {
        return (string) Stringy::create($str, $encoding)
            ->safeTruncate($length, $substring);
    }
```

That is, [127 lines](https://github.com/danielstjules/Stringy/blob/master/src/StaticStringy.php) vs [1000+](https://github.com/danielstjules/Stringy/blob/1.x/src/StaticStringy.php) (when accounting for missing methods)

`StaticStringy` offers little advantage over the mbstring extension on its own. Hence why I had tried deprecating it with the release of 2.0.

**Comment by Bilge** [comment]
>StaticStringy offers little advantage over the mbstring extension on its own.

That seems like an outrageous claim. Stringy exports many functions that mbstring does not.

Back to the issue at hand, if line count is really your nemesis then either approach is fine with me, but I still distinctly prefer v1 because it is fully documented should I ever wish to jump into the documentation from my editor; which I often do.

**Comment by danielstjules** [comment]
Closing via https://github.com/danielstjules/Stringy/commit/63109ce85c7f3f27ecf75ad3c58ff0580ced16b6
