### ISSUE TITLE
Error: Call to undefined function Stringy\mb_regex_encoding()

### ISSUE THREAD

**Issue by Nayjest** [danielstjules/Stringy#129]
Looks like becouse of removing ext-mbsring from composer.json default Heroku PHP buildpack not installs it during deploy. So it uses mb_regex_encoding from polyfill and considering that it's not a php function, it's required to use "\" before function name to specify root namespace.

**How to reproduce**: I suggest to run tests on environment without ext-mbstring
**PHP**: 7.0.4

**Comment by danielstjules** [comment]
Darn, this wasn't caught by CI since all envs have mb_string installed by default https://github.com/danielstjules/Stringy/blob/master/.travis.yml

**Comment by danielstjules** [comment]
A little tough to do right now https://github.com/travis-ci/travis-ci/issues/4701#issuecomment-199454113

But I'll push a patch release. Sorry!

**Comment by danielstjules** [comment]
Published 2.3.1 with a fix, sorry again!
