### ISSUE TITLE
Expose method getStr()

### ISSUE THREAD

**Issue by bryglen** [danielstjules/Stringy#133]

**Comment by danielstjules** [comment]
But why? Would it just be an alias for `__toString`? Can you show any examples in which it would be necessary?

**Comment by bryglen** [comment]
toString only works when you are doing 'echo'

But when you store it on the db or pass it into the 3rd party api, it will save as a object and not the magic method __toString itself 

such examples are

$api->post(['description'=> s('some_long_description')->truncate(10)])

This method return stringify object instead of the truncated string.

**Comment by danielstjules** [comment]
That's not true. It works with a lot of functions that act on strings. You can also cast using `(string) $strObject`

**Comment by bryglen** [comment]
Ive also try to cast it as a string but it was still giving object,

Try it like this

json_encode(['description'=>s('longlong')->truncate(200)]); and save to the DB, you will see the description will turn as empty {}

I'm working something and used it like that, when i try to echo it works fine but when i try to save it to the db or to the API it will save as an object.

**Comment by bryglen** [comment]
I can make PR if you want.. I am really 100percent sure that it doesn't work when passing to thr API or saving directly to the db without echo.. I am using php 5.6 btw.

**Comment by danielstjules** [comment]
```php
var_dump(json_encode([
  'description'=>(string) s('longlong')->truncate(200)
]));
// => string(26) "{"description":"longlong"}"
```

**Comment by danielstjules** [comment]
At that point,

``` php
// it's whether or not this
s('longlong')->truncate(200)->getString();
// looks nicer than this
(string) s('longlong')->truncate(200);
```

**Comment by bryglen** [comment]
like I've said any printable will work fine except saving directly to the DB

**Comment by bryglen** [comment]
Okay, if typecasting will work for now. that would be great. I will test again on my end and see if its still an issue. thanks
