### ISSUE TITLE
Is it supposed to work on configurations without mbstring module installed?

### ISSUE THREAD

**Issue by chetzof** [danielstjules/Stringy#134]
I saw the mention in description that it uses the polyfill when the module is not installed, however seems that it's not sufficient?

`Fatal error: Uncaught Error: Call to undefined function mb_regex_encoding()`

The product that uses Stringy is supposed to be distributed to users that may be unable to install the mbstring module.

Tested on php PHP 7.0.4-6+deb.sury.org~trusty+3

**Comment by GrahamCampbell** [comment]
Only 2.3 or newer will working without the mb string extension.

**Comment by chetzof** [comment]
I am using the latest version installed from composer: 2.3.1

**Comment by GrahamCampbell** [comment]
Where is the call to mb_regex_encoding made?

**Comment by GrahamCampbell** [comment]
https://github.com/symfony/polyfill-mbstring/blob/master/Mbstring.php#L52

**Comment by GrahamCampbell** [comment]
It seems the polyfil doesn't provide this function...

**Comment by GrahamCampbell** [comment]
Ping @lucasmichot. Your PR is broken.

**Comment by lucasmichot** [comment]
No it's not
Someone added delimit function
Which was somehow not properly tested

Le mercredi 20 avril 2016, Graham Campbell <notifications@github.com> a
écrit :

**Comment by chetzof** [comment]
Indeed, i was using `delimit` function...

**Comment by lucasmichot** [comment]
Strange the tests could pass for this new function
I'll Have a look in 1 hour

**Comment by danielstjules** [comment]
`mb_regex_encoding` is used in several places

**Comment by danielstjules** [comment]
Since we're blocked on travis for disabling the module in CI, what's the quickest path forward? Are all other mb_ functions used in Stringy polyfilled? An upstream PR would probably work well.

**Comment by GrahamCampbell** [comment]
You're not blocked if you set sudo to true.

**Comment by danielstjules** [comment]
And just building it from source? Eh, it's fine either way. But that doesn't resolve the more pressing issue.

**Comment by danielstjules** [comment]
> And just building it from source?

Actually, I'd rather not to do that. Having phpunit load autload.php and bringing in the polyfill bumped CI times from ~1.5 minutes to 11+ minutes. Building PHP from source for each job just to have the flexibility of specifying the modules to compile seems ridiculous for what is a small string library.

**Comment by danielstjules** [comment]
Will have time to take a look at this later today. I'm thinking we can just poylyfill the fn ourselves until available in `symfony/polyfill-mbstring` :)

**Comment by danielstjules** [comment]
Looks like Stringy uses the following functions which are not polyfilled:
* mb_ereg_replace
* mb_ereg_match
* mb_regex_encoding
* mb_split

**Comment by danielstjules** [comment]
Here's what I think we can achieve. That Stringy fully works without the mb module for utf8. But for other multibyte encodings, the module will be required.

**Comment by danielstjules** [comment]
APIs for mb_ereg* and preg are so different for regexp handling it's not worth using preg as a fallback. I'm going to eliminate all mb_ereg use in the internals, which will have an impact on the public API and likely force a new major release due to BC.
