### ISSUE TITLE
Extending Base Component

### ISSUE THREAD

**Issue by heera** [danielstjules/Stringy#140]
When I tried to extent the base Stringy class I've noticed some issues. These are:

<pre>
class StringyExtended extends Stringy {
    public function hasUpperCase()
    {
        // Match uppercase anywhere in the string
        $patternForUpperCase = ".*([[:upper:]])";
        return (bool) mb_ereg_match($patternForUpperCase, $this->str);
    }
}
</pre>

I couldn't use `Stringy::matchesPattern` because it's a private method and the `$str` is also declared as private so consider these issues. Otherwise, it's a great library. Probably, `protected` would solve these issues but it's still possible other way.

**Comment by danielstjules** [comment]
Thanks! This has since been fixed :)
