### ISSUE TITLE
Stringy.php : typo in class name

### ISSUE THREAD

**Issue by ChristopheBrun** [danielstjules/Stringy#142]
In src/Stringy.php, l.1862 : 

`throw new \**RuntimeExpception**('Stringy method requires the ' .
    'mbstring module for encodings other than ASCII and UTF-8');`

Fix : 
`throw new \RuntimeException(...)`

**Comment by ChristopheBrun** [comment]
Also, it could be interesting to add in the error message the encoding actually used. Something like : 
`throw new \**RuntimeException**('Stringy method requires the ' . 'mbstring module for encodings other than ASCII and UTF-8. Encoding used : ' / $this->encoding);`

**Comment by danielstjules** [comment]
Thanks!
