### ISSUE TITLE
mb_string -> slugify() unexpected behavior

### ISSUE THREAD

**Issue by odahcam** [danielstjules/Stringy#144]
`S::create('área')->slugify()`

Instead of converting characters like `área` to `area`, the method converts `área` to `225rea`.

**Comment by danielstjules** [comment]
What's `S::create('área')->getEncoding()` in this case? Not UTF8? Do you have mbstring installed?

Works for me locally:
``` php
$ php -a
Interactive shell

php > require 'vendor/autoload.php';
php > echo Stringy\Stringy::create('área')->slugify();
area
```

**Comment by danielstjules** [comment]
If ` \mb_internal_encoding()` is not UTF-8, I'd suggest updating it, since that's the default used by Stringy: https://github.com/danielstjules/Stringy#createmixed-str--encoding- If you don't want to specify a global encoding though, you can also do:
``` php
Stringy\Stringy::create('área', 'UTF-8')->slugify();
```

**Comment by odahcam** [comment]
I have `mb_internal_encoding('UTF-8')` set before run the slugify method, everything is set to UTF-8.

As I said in the issue title, I'm using the method in a `mbstring` (mb_string -> slugify()).

I need to say that the string comes from a XML CDATA node.

Take a look on this:

`object(library\Stringy\Stringy)#5 (2) { ["str":protected]=> string(19) "225rea" ["encoding":protected]=> string(5) "UTF-8" }`

**Comment by danielstjules** [comment]
Can you post a reproduce case that you can run from the repl? Like the example I posted in https://github.com/danielstjules/Stringy/issues/144#issuecomment-251512991

**Comment by odahcam** [comment]
Well, I need to apologize for this noob issue, it was an ridiculous lack of attention from me. I was trying to make slug from a html encoded string, Browsers don't seem to show html encoding like `&#225;` in **DevTools** anymore, it simply parses the html above like `á`.

Well, at all I made a function to decode these htmlentities:

    <?php // someStdClass
       
       /**
         * @author Luiz Filipe Machado Barni <luizfilipe2557@gmail.com>
         *
         * @param {string} $str String to decode.
         * @return {string}
         */
        public static function htmlentities_decode($str)
        {
            $str = html_entity_decode($str, ENT_COMPAT, mb_internal_encoding());
            // replace numeric entities
            $str = preg_replace_callback('~&#x([0-9a-f]+);~i', function ($m) { return chr(hexdec($m[1])); }, $str);

            $str = preg_replace_callback('~&#([0-9]+);~', function ($m) { return chr($m[1]); }, $str);
            // replace literal entities
            $trans_tbl = array_flip(get_html_translation_table(HTML_ENTITIES));

            return strtr($str, $trans_tbl);
        }

**Comment by danielstjules** [comment]
@odahcam ah, glad you figured it out! Sounds like this can be closed then? :)

**Comment by odahcam** [comment]
Sure you can close, I don't know If you already have a method like this, but I would be glad for creating a pull request with my method after improve it.

**Comment by odahcam** [comment]
My decode function:

``` php
// someStdClass

/**
 * @author Luiz Filipe Machado Barni <luiz@h2k.com.br>
 *
 * @param {string} $str String to decode
 *
 * @return {string}
 */
public static function htmlentities_decode($str)
{
    if (function_exists('html_entity_decode')) {
        $str = html_entity_decode($str, ENT_QUOTES, mb_internal_encoding());
    } else {
        // replace numeric entities
        $str = preg_replace_callback('~&#x([0-9a-f]+);~i', function ($m) {
            return chr(hexdec($m[1]));
        }, $str);
        $str = preg_replace_callback('~&#([0-9]+);~', function ($m) {
            return chr($m[1]);
        }, $str);

        // replace literal entities
        $str = strtr($str, array_flip(get_html_translation_table(HTML_ENTITIES)));
    }

    return $str;
}
```
