### ISSUE TITLE
gain toAscii method please

### ISSUE THREAD

**Issue by newbie78** [danielstjules/Stringy#156]
I found missing variants in $charsArray :
'a'=>'ä'
'ae'=>'æ'
'ss'=>'ß'
'U'=>'Ў'
'u'=>'ў'

tnx for your exellent package!

**Comment by danielstjules** [comment]
Thanks! ä, æ and ß were already there, but I'll add the other two!

**Comment by danielstjules** [comment]
Added in https://github.com/danielstjules/Stringy/commit/e8afcffc7c3ca4cd6ead74d57f6c4c6098fe5499 :)
