### ISSUE TITLE
`toAscii` method should not convert @ to "at"

### ISSUE THREAD

**Issue by e1himself** [danielstjules/Stringy#162]
I think `toAscii` method should not convert @ to "at" 
as `@` sign is already 100% ascii.

Though "@" => "at" conversion can absolutely be part of `slugify()`.
But `toAscii` should do exactly what method name says.

------ 

Just had a few hours of debugging. 
Turned out that after upgrading Stringy to 2.2.0+ our emails addresses to-ascii downgrading was broken.

Example:

```php
$email = "cécile@example.com";
$expected = "cecile@example.com";
$actual = (string) StaticStringy::toAscii($email); // produces cecileatexample.com

echo $expected == $actual ? 'Pass' : 'Fail'; // Fails

```

**Comment by danielstjules** [comment]
Sorry about that, you're absolutely right and this has been fixed in https://github.com/danielstjules/Stringy/commit/eb13cc35d6a133d413db89203f8b8faa580f108f

**Comment by e1himself** [comment]
Wow! 
That was lightingly fast @danielstjules !
Mille thanks! :+1:
