### ISSUE TITLE
Camelize doesn't work properly

### ISSUE THREAD

**Issue by simPod** [danielstjules/Stringy#184]
When using camelize on strings like `XY_Z`, it produces `xYZ` but I believe it should instead do `xyZ`

Or am I mistaken? Thanks!

**Comment by noraheuer** [comment]
you are mistaken ... it does not change existing caps (except the first one) .... think about it .... your xyZ would be turned into xyz on the second run if you had it your way.

**Comment by simPod** [comment]
You're right, thanks!
