### ISSUE TITLE
Code duplication between Stringy and StaticStringy

### ISSUE THREAD

**Issue by vlakoff** [danielstjules/Stringy#65]
You'll agree maintaining 2 codebases (regular and static) is easily conceivable as nightmarish.

Instead of waiting to see if one of the APIs is dying, how about using `__callStatic()` for the static class? Is it desirable, doable?

**Comment by danielstjules** [comment]
My only concern is that the API isn't really self-documenting anymore when looking through that file's code. You'd end up having to write a class docblock, and list all methods using `@method`. That will end up very ugly for anyone who is only using StaticStringy (which is surprisingly popular compared to the OO interface).

**Comment by vlakoff** [comment]
(conflict) Also, looks like we can't create a generic `__callStatic()`, because we would need to grab the last argument as `$encoding`, but it's not present in all methods, and all the optional arguments break this... Still, it *might* be feasible, removing the `$encoding`'s from static class...

**Comment by danielstjules** [comment]
You'd have to build up arrays of methods using the different method signatures. Sure, reduces code, but is quite ugly.

**Comment by vlakoff** [comment]
So ugly, indeed.

This makes me think of another subject: some way to specify charset only once instead of repeatedly, without relying too much on global state. A config item, also changeable as runtime? But let's keep that for later.

As we are talking about the global API, maybe the best is just to wait a bit and see what are the popular requests.

**Comment by danielstjules** [comment]
Agreed. If StaticStringy wasn't so popular, I'd be more inclined. From the projects I've seen, I have the impression that it's more popular than Stringy - it's the biggest reason I'd rather keep the duplication, as it offers better documentation of the API.

I won't close this issue since you'd might like to continue the discussion, but feel free if you'd like to do so yourself.

**Comment by danielstjules** [comment]
If you don't mind, I'm gonna close the PR since there hasn't been any discussion for a couple weeks. But let me know if you had any other ideas.
