### ISSUE TITLE
Cannot redeclare Stringy\create()

### ISSUE THREAD

**Issue by crynobone** [danielstjules/Stringy#69]
```
Fatal error: Cannot redeclare Stringy\create() (previously declared in /Users/crynobone/.composer/vendor/danielstjules/stringy/src/Create.php:14) in /Users/crynobone/Projects/orchestra/testbench/vendor/danielstjules/stringy/src/Create.php on line 17
```

Since this package is now used by `illuminate/support` which commonly installed per project and globally the function need to be wrapped inside `function_exists()` to work properly. 

See composer/composer#3003 and reactphp/promise#23 for reference.

**Comment by danielstjules** [comment]
Thanks for pointing that out! Should be fixed in https://github.com/danielstjules/Stringy/commit/d6fa00bb1cc28923c6729da2c0ea3c71977532a9

**Comment by crynobone** [comment]
Can you tag a minor release, e.g `1.8.1` so we can grab the fix :)

Thanks.

**Comment by danielstjules** [comment]
https://github.com/danielstjules/Stringy/releases/tag/1.8.1 :)

**Comment by markuskoehler** [comment]
I just experienced this error when running automatic tests through Atlassian Bamboo.

Using v1.8.1 doesn't help and 1.10.* doesn't work as well. Is it possible to fix this?

    Updating dependencies (including require-dev)
      - Removing danielstjules/stringy (1.8.1)
      - Installing danielstjules/stringy (1.10.0)
        Loading from cache

    Writing lock file
    Generating autoload files
    > php artisan optimize
    PHP Fatal error:  Cannot redeclare class Stringy\Stringy in /opt/atlassian/bamboo/xml-data/build-dir/MKIT-WDSA-JOB1/vendor/danielstjules/stringy/src/Stringy.php on line 5

**Comment by danielstjules** [comment]
Do you have a small reproduce case? Is it possible that your autoloading is indeed trying to load Stringy twice?

**Comment by markuskoehler** [comment]
Well, initially I did not call it explicitely in my composer.json, but it is of course a dependency of Laravel Framework (v.5.1.19), so I cannot get rid of it. This exception only occurs when running the build in Atlassian Bamboo, not in my local dev environment or on any other dev environment where I have worked with Laravel previously.

Would it maybe help to check if Stringy is already initialized when trying to redeclare it? Can you implement such check?

**Comment by danielstjules** [comment]
It's possible to prevent it using something like `if (!class_exists('String\Stringy')) { }`, but Stringy isn't at fault for this error. Something is trying to load the file a second time, be it composer, bamboo, etc.

**Comment by thinkspill** [comment]
I happened upon this thread while researching this same issue. After a bit more poking, I discovered that I was running PHPUnit without passing in the `--bootstrap phpunit.xml` argument, which caused phpunit to try executing all tests from the root of my project, including all tests in `vendor/`. Passing this argument to phpunit made this particular error go away (and on to the next one... :).

**Comment by danielstjules** [comment]
Thanks for explanation @thinkspill ! Super helpful :)

**Comment by taviroquai** [comment]
OMG, I assumed that running phpunit from Laravel folder would load phpunit.xml by default. I was getting crasy about this error.
Nice catch @thinkspill
