### ISSUE TITLE
PHP bug with mb_strtoupper and mb_strtolower

### ISSUE THREAD

**Issue by takobell** [danielstjules/Stringy#71]
Just got bitten by this bug:  https://bugs.php.net/bug.php?id=47742

Stringy's [toLowerCase](https://github.com/danielstjules/Stringy/blob/master/src/Stringy.php#L726) and [toUpperCase](https://github.com/danielstjules/Stringy/blob/master/src/Stringy.php#L739) use them.

This seems to be a workaround that works for me:

    mb_convert_case($string, MB_CASE_UPPER, 'UTF-8');
    mb_convert_case($string, MB_CASE_LOWER, 'UTF-8');

Interestingly enough, you're already using `mb_convert_case` in the [toTitleCase()](https://github.com/danielstjules/Stringy/blob/master/src/Stringy.php#L713) method.

**Comment by danielstjules** [comment]
@takobell Can you post an example string/expected-output as well as the PHP version used?

I tried replicating the problem with a few strings from the bug report (which used PHP 5.2) and haven't been able to reproduce it yet.

**Comment by danielstjules** [comment]
I just pushed up a branch as an example:
https://github.com/danielstjules/Stringy/commit/7e04a4a3ac8325f24ca635d9a42869913fbd19ca
You can see that it passes: https://travis-ci.org/danielstjules/Stringy/jobs/46413944

I'll happily switch to mb_convert_case - I'd just like to figure out a failing test beforehand first, to avoid regression.

**Comment by takobell** [comment]
O.K., when I said "just got bitten", that was a bit of a stretch, it was back in March '14.

We're looking to integrate Stringy in our distributed app to replace all of our custom string manipulation methods.

We made the above change in response to a support ticket that came in that we were able to reproduce, but I'm having a hard time finding the original ticket that had string that would fail.

I'll keep digging, but I suspect it was either some 4-byte Chinese characters or some sequence of RTL Arabic characters that were involved.

**Comment by vlakoff** [comment]
I could reproduce the issue on [sandbox.onlinephpfunctions.com](http://sandbox.onlinephpfunctions.com/) and [phptester.net](http://phptester.net/). But I don't know what is the cause…

**Comment by vlakoff** [comment]
Looks like it's just that the bug reporter should have done `mb_strtoupper($s, 'UTF-8')` instead of `mb_strtoupper($s)`…

**Comment by takobell** [comment]
@vlakoff Ahh, nice catch.  `$test = echo mb_strtolower('ايران لا ترى تغييرا في الموقف الأمريكي');` produces garbled output for me, but `$test = echo mb_strtolower('ايران لا ترى تغييرا في الموقف الأمريكي', 'UTF-8');` works fine, which Stringy is already accounting for.

**Comment by GrahamCampbell** [comment]
It's probably doing that because you haven't set your default encoding correctly in your php config.

**Comment by takobell** [comment]
Just just testing on: http://sandbox.onlinephpfunctions.com/

If I add `mb_internal_encoding('UTF-8');` to the script, then the 2nd parameter isn't necessary.

**Comment by vlakoff** [comment]
So, current Stringy code is just fine :)

**Comment by takobell** [comment]
Agreed. I can't even find the original ticket that prompted us to make the change, but I'm pretty satisfied with this.
