### ISSUE TITLE
Posix ereg vs. PCRE

### ISSUE THREAD

**Issue by takobell** [danielstjules/Stringy#76]
Not so much an issue as a implementation question.

Was there a specific reason for using `mb_ereg_match` in matchPattern() vs. `preg_match`?

For example, the former would use `[[:upper:]]` to find uppercase letters and the latter would use `\p{Lu}`.

I know Posix has been around longer, so maybe PCRE isn't as multibyte capable?  Just trying to come to grips with the more awkward (to me) Posix syntax.

For example, if I wanted to add a `hasUpperCase()` method to see if a string had *any* uppercase character in it, it looks like `.*[[:upper:]]` is the pattern that works, although my brain wants to interpret that as "the first character is upper or lowercase and the rest are uppercase".

**Comment by danielstjules** [comment]
My idea at the time was to offer support for other multibyte encodings. preg_match can only support UTF-8 (and potentially other members of the unicode family? I know PCRE can). mb_ereg_match, however, can support UTF-16, UTF-32, Big5, EUC-KR, HZ, ISO-2022-JP, among many others.

**Comment by danielstjules** [comment]
At this point, the library has 6 methods that rely on PCRE when they could be updated to use mb_* functions. I don't include tidy() in that count, due to it targeting Windows-1252 specifically.

**Comment by takobell** [comment]
Fair enough... thanks for the explanation, @danielstjules.
