### ISSUE TITLE
titleize() works unexpectedly on strings with all caps

### ISSUE THREAD

**Issue by stevenmusumeche** [danielstjules/Stringy#82]
I was expecting the titilize method to return "Title Case" for the string "TITLE CASE".  Instead, it stayed all caps.  I had to call toLower, then titleize to get the desired result.

**Comment by danielstjules** [comment]
Thanks for pointing that out! Looking at the rails titleize source, your expected behavior is correct, since `underscore` converts to lower case:
``` ruby
# File activesupport/lib/active_support/inflector/methods.rb, line 133
def titleize(word)
  humanize(underscore(word)).gsub(/\b(?<!['â`])[a-z]/) { $&.capitalize }
end
```

**Comment by stevenmusumeche** [comment]
Would you like for me to create a pull request? I've never done it before but I'm not opposed to trying.

**Comment by danielstjules** [comment]
I'm actually not sure where I stand on this change, to be honest. I kinda like that:
```
'i like to watch DVDs at home' => 'I Like to Watch DVDs at Home'
// Rather than
=> 'I Like to Watch dvds at Home'
```

**Comment by danielstjules** [comment]
@stevenmusumeche I'm thinking this should be fixed to be inline with other libraries. However, while it's a bug, it may be a breaking change requiring a new major version to maintain semver.

**Comment by stevenmusumeche** [comment]
Understood. Would you like me to create a PR now?

**Comment by danielstjules** [comment]
If you'd like to! Otherwise I'll be working on it today or tomorrow. Please target the 2.0.0 branch if you decide to, as it's a breaking change.

**Comment by danielstjules** [comment]
Fixed in https://github.com/danielstjules/Stringy/commit/fa22b94abfb9ef2fab829d874183257ab9d8c553

Thanks again!

**Comment by stevenmusumeche** [comment]
:+1:
