### ISSUE TITLE
"Between" function

### ISSUE THREAD

**Issue by darkoromanov** [danielstjules/Stringy#83]
It would be nice if the "between" function was available. What I man is this function: http://stringjs.com/#methods/between-left-right

**Comment by danielstjules** [comment]
Might be a good addition, but I wouldn't want people thinking they could parse HTML with that function (as shown in those examples):
``` javascript
S('<a href="#foo" class="example">bar</a>').between('<a>', '</a>').s
// => " href="#foo" class="example">bar"
```

Could you post an example use-case?

**Comment by darkoromanov** [comment]
Well, sure. I wouldn't do that, I need it to avoid the regex complexity when I need to find the text (if any) between "(" and ")" inside a strings like "Lorem (maybe) ipsum".

**Comment by danielstjules** [comment]
```javascript
S('Lorem (maybe) (hmm) ipsum').between('(', ')').s
// => "maybe"
'Lorem (maybe) (hmm) ipsum'.match(/\(([^\)]*)\)/);
// => ["(maybe)", "maybe"]
```

Alright, I see your point there. :)

**Comment by vpassapera** [comment]
I already did something like this in my fork @danielstjules if you want to take a look at it (or perhaps you can come up with a better implementation since mine is a bit hackish)

https://github.com/TheDevNetwork/PhpTypes#substrfromto

**Comment by danielstjules** [comment]
@darkoromanov @vpassapera If either of you'd like to submit a PR, I'll merge this functionality. :) Otherwise I'll probably add it this weekend.

**Comment by danielstjules** [comment]
Done in https://github.com/danielstjules/Stringy/commit/342ef7c3dd4f68e773e0c59701ec77ec18b08f9b :) Thanks!

**Comment by darkoromanov** [comment]
thanks!
