### ISSUE TITLE
Usage of "use function" namespaced method breaks dependencies

### ISSUE THREAD

**Issue by shehi** [danielstjules/Stringy#85]
https://github.com/danielstjules/Stringy/blob/master/tests/CreateTest.php#L5

The statement of ```use function ...``` is a feature which comes in PHP 5.6 (http://php.net/manual/en/language.namespaces.importing.php). Your ```composer.json``` file however, declares that this package is compatible with PHP 5.3+. This mistake causes my build scripts to break. Please either fix ```composer.json``` declaration, or don't use namespaced function calls. Thanks!

**Comment by shehi** [comment]
Oops, my mistake. The code mentioned is a unit test. My PHPUnit installation somehow included all vendor package tests in deployment as well, which led to running your tests in my non-PHP-5.6 environment. Closing this one.

**Comment by danielstjules** [comment]
Glad things work :)

**Comment by yizhihou2** [comment]
I had the same issue when I ran `composer update`: http://stackoverflow.com/questions/33663378/how-to-revert-back-composer-update , I tried to remove the test folder but it still didn't work, `rm -rf tests/`. How can I fix it? Thanks!
