### ISSUE TITLE
New substrings and type methods

### ISSUE THREAD

**Issue by TCB13** [danielstjules/Stringy#86]
Hello,

I'm about to fork this in order to implement the following methods:

`containsInt()`: Checks if the string contains an integer value.
`containsFloat()`: Checks if the string contains an float value.
`containsNumber()`: Checks if the string contains a number integer or float.
`isEmpty()`: Checks if the string is empty (doesn't contain any char).
`afterFirstSubstring()`: Returns a substring of the input string containing everything after first occurrence of a given substring
`afterLastSubstring()`: Returns a substring of the input string containing everything after last occurrence of a given substring
`beforeFirstSubstring()`: Returns a substring of the input string containing everything before first occurrence of a given substring
`beforeLastSubstring()`: Returns a substring of the input string containing everything before last occurrence of a given substring

However I'm not sure about the naming convention I should be using. I had this methods on a String class I've been developing for years but now I'm about to move to Stringy.

What do you guys think?

Thank you.

**Comment by danielstjules** [comment]
Closing thanks to https://github.com/danielstjules/Stringy/pull/87 :)
