### ISSUE TITLE
applyDelimiter should have a public implementation

### ISSUE THREAD

**Issue by Bilge** [danielstjules/Stringy#88]
`applyDelimiter` should be public or have a public implementation, e.g. `delimit()`. Stringy currently only supports two fixed implementations, `dasherize` and `underscored`, which are wrong for many reasons:

* Of these fixed implementations, one is a verb and one is an adjective; i.e. `underscored` should actually be `underscore`.
* I may want to delimit using a space character but I can't because the underlying delimit implementation has `protected` access.
* Stringy should expose the delimit functionality directly making these hard coded variants obsolete.

**Comment by danielstjules** [comment]
* `underscored` was influenced by https://github.com/epeli/underscore.string#underscoredstring--string though I agree it would be better named `underscore`.
* What's wrong with dasherize as a name? It's familiar for many https://github.com/epeli/underscore.string#dasherizestring--string http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-dasherize http://stringjs.com/#methods/dasherize If you're arguing it's a terrible name, you won't see me refuting that.
* Even if Stringy exposes applyDelimiter directly, we'll still need public dasherize and underscored functions

Anyway, good idea - Stringy would benefit from applyDelimiter being public.

**Comment by Bilge** [comment]
Just don't call it `applyDelimiter`.

**Comment by danielstjules** [comment]
Done via https://github.com/danielstjules/Stringy/commit/7763df3c3b85ca417a08b30e71f6aa61686c7f78
Thanks again!

**Comment by Bilge** [comment]
No problem, I'm glad you have nothing better to do with your life.

**Comment by danielstjules** [comment]
haha friendly as ever
