### ISSUE TITLE
Should camelize() lower uppercase letters?

### ISSUE THREAD

**Issue by CarlosGarcell** [danielstjules/Stringy#90]
I was testing the class on a project I'm working on with Laravel, and I was using camelize() to return strings the way they should be used when you name functions, now, if I send a string like this one "MY FUNCTION", it would return "mYFUNCTION". 

Another case is when you type a string like "TeStInG ClAsS", it would output the following "teStInGClAsS".

Is this intended behavior, or should it return the string fully camelized as when you send through a lower case one?

**Comment by danielstjules** [comment]
http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-camelize
I suppose you're right! The function should lowercase first. Will fix as part of the 2.0.0 branch.

**Comment by danielstjules** [comment]
Looks like string.js and underscore.string do this wrong as well. Looking into it.

**Comment by danielstjules** [comment]
I think this will have to be summed up as intended behavior. There's no way of knowing what you're passing is an acronym without some comprehensive list, which is unrealistic. For example, camelize('ServeHTTP') would result in serveHTTP. If we were to lowercase beforehand, we'd force "serveHttp" which isn't necessarily correct. Whether or not acronyms should receive special treatment is a stylistic choice I'd rather not impose: https://en.wikipedia.org/wiki/CamelCase#Programming_and_coding
