### ISSUE TITLE
Continous Integration Failing

### ISSUE THREAD

**Issue by rossedman** [danielstjules/Stringy#92]
I don't think this directly has to do with this but I thought I would ask. I have been building a CI pipeline for a Laravel app with a PHPUnit testing suite and for days I have been tracing errors back to 

`use function Stringy\create as s;`

in the `CreateTest` class. I don't have this problem when I run it locally but for whatever reasons PHPUnit running in my CI container hates this and causes PHPunit to exit with a 255 code. Do you have any idea why this may be? Tried with PHP 5.5.9 and PHP 5.6

**Comment by rossedman** [comment]
Problem solved. For whatever reasons the CI was running all tests in vendor folder.

**Comment by danielstjules** [comment]
Weird, but glad it was fixed!

**Comment by rossedman** [comment]
@danielstjules It must have just hit this package first. That's all I can come up with.
