### ISSUE TITLE
2.0.0 preview

### ISSUE THREAD

**Issue by danielstjules** [danielstjules/Stringy#95]
Currently working on it in the https://github.com/danielstjules/Stringy/tree/2.0.0 branch. Welcome any input :)

**Comment by GrahamCampbell** [comment]
`2.0` would be a better branch name. Then composer automatically releases that it's `2.0.x-dev`.

**Comment by danielstjules** [comment]
You're probably right! Since things were quiet though, I decided to cut the branch and release it
