### ISSUE TITLE
Instantiate without string for Laravel IoC

### ISSUE THREAD

**Issue by DraperStudio** [danielstjules/Stringy#97]
Is there any way to get an instance of Stringy without passing a string to the constructor since StaticStringy has been removed?

I need to have Stringy in the IoC container which would usually be just this short piece.

```php
$this->app->singleton('stringy', function ($app) {
    return new Stringy();
});
```

The issue is that Stringy expects the first parameter to be a string and since calling the facade would be something like `Stringy::slugify('fòô     bàř')` there is nothing I can pass to the `new Stringy()` which is why I would need `new StaticStringy()` which works.

So how would I put Stringy behind a Facade now that StaticStringy is gone?

**Comment by danielstjules** [comment]
Just wondering, what did things look like when using `StaticStringy`?

**Comment by danielstjules** [comment]
@GrahamCampbell any suggestions here?

**Comment by danielstjules** [comment]
I could make the string an optional arg for the constructor and create method, resulting simply in an empty string. That is, same behavior as `return new Stringy('');`

**Comment by DraperStudio** [comment]
With `StaticStringy` it was just the following and that is what I am currently using with ~1.9.

```
$this->app->singleton('stringy', function ($app) {
    return new StaticStringy();
});
```

**Comment by danielstjules** [comment]
Fixed via https://github.com/danielstjules/Stringy/commit/e237f30d94cadefdbea6a9ca3f9406b3167fffe6
