### ISSUE TITLE
[Proposal] StaticStringy as separate package

### ISSUE THREAD

**Issue by DraperStudio** [danielstjules/Stringy#98]
So now that `StaticStringy` has been removed for 2.0 (https://github.com/danielstjules/Stringy/issues/93) I already hade a few situations where I needed the `StaticStringy` class because I had to inject it or something like that.

So my proposal would be that `StaticStringy` would be brought back to life into a separate package like `danielstjules/staticstringy` which would only offer the `StaticStringy` class. This would make it optional and not clutter the core package but we would still have the advantages of it.

So would this be a possibility or is `StaticStringy` gone for good and if I wanted to use `StaticStringy` post 2.0 I should create a package for it myself?

**Comment by danielstjules** [comment]
I can whip up a quick package using __callStatic for this.

**Comment by DraperStudio** [comment]
Would be great if you could do that some day! :+1:

**Comment by danielstjules** [comment]
Brought it back in https://github.com/danielstjules/Stringy/commit/e237f30d94cadefdbea6a9ca3f9406b3167fffe6 Will do a new release soon. Thanks again!
